version: "3.5"
services:
  course-db:
    image: mysql:latest
    volumes:
      - course-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "t3c-demo"
      MYSQL_DATABASE: "t3c-demo"
      MYSQL_USER: "t3c-demo"
      MYSQL_PASSWORD: "t3c-demo"
    networks:
      - t3cnet

  course-directory:
    image: mortht/t3c-course-directory:latest
    depends_on:
      - course-db
    ports:
      - 80:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://t3c_course-db:3306/t3c-demo"
      SPRING_DATASOURCE_USERNAME: "t3c-demo"
      SPRING_DATASOURCE_PASSWORD: "t3c-demo"
      T3C_DEMO_EMPLOYEE_SERVICE_URL: "http://t3c_employee-service:8080/employee"
    networks:
      - t3cnet
    deploy:
      replicas: 3
#      restart_policy:
#        condition: on-failure
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 50M

  employee-service:
    image: mortht/t3c-employee-service:latest
#    ports:
#    - 81:8080
    networks:
      - t3cnet

volumes:
  course-db-data:

networks:
  t3cnet:
     driver: overlay
     attachable: true