version: "3.6"
services:
  course-db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - course-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "t3c-demo"
      MYSQL_DATABASE: "t3c-demo"
      MYSQL_USER: "t3c-demo"
      MYSQL_PASSWORD: "t3c-demo"

  course-directory:
    image: mortht/t3c-course-directory:latest
    depends_on:
      - course-db
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://course-db:3306/t3c-demo"
      SPRING_DATASOURCE_USERNAME: "t3c-demo"
      SPRING_DATASOURCE_PASSWORD: "t3c-demo"
      T3C_DEMO_EMPLOYEE_SERVICE_URL: "http://employee-service:8080/employee"

  employee-service:
    image: mortht/t3c-employee-service:latest
    restart: always
    ports:
      - 8081:8080

volumes:
  course-db-data: